GET http://localhost:3001/api/users/

###
GET http://localhost:3001/api/users/id/

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
  "username": "test1",
  "name": "Test 1",
  "password": "testpassword"
}

###
PUT http://localhost:3001/api/users/id/ HTTP/1.1
content-type: application/json

{
  "username": "test1",
  "name": "Test 1",
  "password": "testpassword"
}

###
DELETE http://localhost:3001/api/users/id/